spring:
  application:
    name: gateway-server
server:
  port: 8000
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
  
management:
  endpoints:
    web:
      exposure:
        include: =*
        
zuul:
  routes:
    ignored-services: =*
    device-service: "/device/**"
    person-service: "/person/**"
    auth-service: "/auth/**"
