spring:
  application:
    name: gateway-server
server:
  port: 8762
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
  
management:
  endpoints:
    web:
      exposure:
        include: =*
        
zuul:
  routes:
    ignored-services: =*
    device-service: "/device/**"
    person-service: "/person/**"
    property-service: "/property/**"
