spring:
  application:
    name: property-service
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
      
server:
  port: 8000
  
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery:8761/eureka/
#      defaultZone: http://localhost:8000/eureka/
