version: "3"
services:  
  discovery:
    image: "openjdk:8-jre-alpine"
    container_name: "discovery-server"
    working_dir: /home/app
    volumes:
      - ../artefacts/discovery/:/home/app
    ports:
      - 8761:8761
    expose:
      - "8761"
    command: >
        sh -c "java -jar discovery-server-0.0.1-SNAPSHOT.jar"
    networks:
      - interna
        
  gateway:
    image: "openjdk:8-jre-alpine"
    container_name: "gateway-service"
    working_dir: /home/app
    volumes:
      - ../artefacts/gateway/:/home/app
    depends_on:
      - discovery
    ports:
      - 8000:8000
    expose:
      - "8000"
    command: >
        sh -c "java -jar gateway-service-0.0.1-SNAPSHOT.jar"
    networks:
      - interna
        
networks: 
  interna:
    driver: bridge