spring:
  application:
    name: gateway-server
server:
  port: 8000
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
  
management:
  endpoints:
    web:
      exposure:
        include: =*
        

      
zuul:
  routes:
    ignored-services: =*
    device-service: "/device/**"