version: "3.5"
services: 
  person:
    image: "openjdk:8-jdk-alpine"
    container_name: "person-service"
    working_dir: /home/app
    volumes:
      - ./:/home/app
    command: >
        sh -c "chmod 777 ./gradlew && ./gradlew clean build && chmod -R 777 person-infrastructure/build/ && java -jar person-infrastructure/build/libs/person-service-1.0.0-SNAPSHOT.jar"   
    networks:
      - phnet
      - internal
      - pgnet-person
      
  person-database:
    image: "postgres"
    restart: always
    container_name: "person-database"
    environment:
      POSTGRES_DB: "person-database"
      POSTGRES_USER: "person_user"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ../../hardware-layer/database/person:/docker-entrypoint-initdb.d
      - pgdata-person
    networks:
      - pgnet-person
      - phnet

volumes:
  pgdata-person: # Volumen para el almacenamiento interno de la base de datos
    name: pgdata-person

networks:
   pgnet-person:
    driver: bridge
   phnet:
    external: true
    name: phnet
   internal:
    external: true
    name: internal
   
