version: "3.5"
services:  
  discovery:
    image: "openjdk:8-jdk-alpine"
    container_name: "discovery-server"
    working_dir: /home/app
    volumes:
      - ./:/home/app
    ports:
      - "8000:8761"
    expose:
      - "8000"
    command: >
        sh -c "chmod 777 ./gradlew && ./gradlew build && java -jar build/libs/discovery-server-0.0.1-SNAPSHOT.jar"
        
    networks:
      - phnet
       
networks: 
  phnet:
    name: phnet
