version: "3.5"
services:  
  property:
    image: "openjdk:8-jdk-alpine"
    container_name: "property-service"
    working_dir: /home/app
    volumes:
      - ./:/home/app
    ports:
      - "8011:8011"
    command: >
        sh -c "chmod 777 ./gradlew && ./gradlew clean build && chmod -R 777 property-infrastructure/build/ && java -jar property-infrastructure/build/libs/property-infrastructure-1.0.0-SNAPSHOT.jar --trace"   
    networks:
      - phnet
      - internal
      - pgnet-property

  property-database:
    image: "postgres"
    restart: always
    container_name: "property-database"
    environment:
      POSTGRES_DB: "property-database"
      POSTGRES_USER: "property_user"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ../../hardware-layer/database/property:/docker-entrypoint-initdb.d
      - pgdata-property
    networks:
      - pgnet-property

volumes:
  pgdata-property:
    name: pgdata-property

networks:
  pgnet-property:
    driver: bridge
  phnet:
    external: true
    name: phnet
  internal:
    external: true
    name: internal
   
