version: "3.5"
services:  
  property:
    image: "java:8"
    container_name: "property-service"
    working_dir: /home/app
    volumes:
      - ./:/home/app
    command: >
        sh -c "chmod 777 ./gradlew && ./gradlew build && java -jar build/libs/property-service-0.0.1-SNAPSHOT.jar"   
    networks:
      - phnet
      - rabbitmq

networks:
  phnet:
    external: true
    name: phnet
  rabbitmq:
    external: true
    name: rabbitmq
