version: "3.5"
services:  
  device:
    image: "openjdk:8-jdk-alpine"
    container_name: "device-service"
    working_dir: /home/app
    volumes:
      - ./:/home/app
    command: >
        sh -c "chmod 777 ./gradlew && ./gradlew clean build && java -jar device-infrastructure/build/libs/device-service-1.0.0-SNAPSHOT.jar"   
    networks:
      - phnet
      - internal
      - pgnet-device

  device-database:
    image: "postgres"
    restart: always
    container_name: "device-database"
    environment:
      POSTGRES_DB: "device-database"
      POSTGRES_USER: "device_user"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ../../hardware-layer/database/device:/docker-entrypoint-initdb.d
      - pgdata-device
    networks:
      - pgnet-device


volumes:
  pgdata-device:
    name: pgnet-device

networks:
  pgnet-device:
    driver: bridge
  phnet:
    external: true
    name: phnet
  internal:
    external: true
    name: internal
