version: "3.5"
services:  
  gateway:
    image: "java:8"
    container_name: "gateway-service"
    working_dir: /home/app
    volumes:
      - ./:/home/app
    ports:
      - "8001:8000"
    expose:
      - "8001"
    command: >
        sh -c "chmod 777 ./gradlew && ./gradlew build && java -jar build/libs/gateway-service-0.0.1-SNAPSHOT.jar"   
    networks:
      - phnet
      - communication
networks:
  phnet:
    external: true
    name: phnet
  communication:
    name: internal
    driver: bridge
