version: "3.5"
services:  
  gateway:
    image: "java:8"
    container_name: "gateway-service"
    working_dir: /home/app
    volumes:
      - ./:/home/app
    ports:
      - "8001:8000"
    expose:
      - "8001"
    command: >
        sh -c "chmod 777 ./gradlew && ./gradlew build && java -jar build/libs/gateway-service-0.0.1-SNAPSHOT.jar"   
    networks:
      - phnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: brokermq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq-broker

networks:
  phnet:
    external: true
    name: phnet
  rabbitmq-broker:
    name: rabbitmq
    driver: bridge
