version: "3.5"
services:  
  gateway:
    image: "openjdk:8-jdk-alpine"
    container_name: "gateway-service"
    working_dir: /home/app
    volumes:
      - ./:/home/app
    ports:
      - "8001:8762"
    expose:
      - "8001"
    command: >
      sh -c "chmod 777 ./gradlew && ./gradlew build && java -jar build/libs/gateway-service-0.0.1-SNAPSHOT.jar"
    networks:
      - phnet

networks:
  phnet:
    external: true
    name: phnet