version: "3.5"
services:  
  gateway:
    image: "java:8"
    container_name: "auth-service"
    working_dir: /home/app
    volumes:
      - ./:/home/app
    command: >
        sh -c "chmod 777 ./gradlew && ./gradlew build && java -jar build/libs/auth-service-0.0.1-SNAPSHOT.jar"   
    networks:
      - phnet

networks:
  phnet:
    external: true
    name: phnet
